// automatically generated by the FlatBuffers compiler, do not modify


// @generated

use core::mem;
use core::cmp::Ordering;

extern crate flatbuffers;
use self::flatbuffers::{EndianScalar, Follow};

#[allow(unused_imports, dead_code)]
pub mod coffee_time {

  use core::mem;
  use core::cmp::Ordering;

  extern crate flatbuffers;
  use self::flatbuffers::{EndianScalar, Follow};
#[allow(unused_imports, dead_code)]
pub mod output {

  use core::mem;
  use core::cmp::Ordering;

  extern crate flatbuffers;
  use self::flatbuffers::{EndianScalar, Follow};
#[allow(unused_imports, dead_code)]
pub mod label {

  use core::mem;
  use core::cmp::Ordering;

  extern crate flatbuffers;
  use self::flatbuffers::{EndianScalar, Follow};

pub enum CoordOffset {}
#[derive(Copy, Clone, PartialEq)]

pub struct Coord<'a> {
  pub _tab: flatbuffers::Table<'a>,
}

impl<'a> flatbuffers::Follow<'a> for Coord<'a> {
  type Inner = Coord<'a>;
  #[inline]
  unsafe fn follow(buf: &'a [u8], loc: usize) -> Self::Inner {
    Self { _tab: flatbuffers::Table::new(buf, loc) }
  }
}

impl<'a> Coord<'a> {
  pub const VT_X: flatbuffers::VOffsetT = 4;
  pub const VT_Y: flatbuffers::VOffsetT = 6;

  #[inline]
  pub unsafe fn init_from_table(table: flatbuffers::Table<'a>) -> Self {
    Coord { _tab: table }
  }
  #[allow(unused_mut)]
  pub fn create<'bldr: 'args, 'args: 'mut_bldr, 'mut_bldr>(
    _fbb: &'mut_bldr mut flatbuffers::FlatBufferBuilder<'bldr>,
    args: &'args CoordArgs
  ) -> flatbuffers::WIPOffset<Coord<'bldr>> {
    let mut builder = CoordBuilder::new(_fbb);
    builder.add_y(args.y);
    builder.add_x(args.x);
    builder.finish()
  }


  #[inline]
  pub fn x(&self) -> i32 {
    // Safety:
    // Created from valid Table for this object
    // which contains a valid value in this slot
    unsafe { self._tab.get::<i32>(Coord::VT_X, Some(0)).unwrap()}
  }
  #[inline]
  pub fn y(&self) -> i32 {
    // Safety:
    // Created from valid Table for this object
    // which contains a valid value in this slot
    unsafe { self._tab.get::<i32>(Coord::VT_Y, Some(0)).unwrap()}
  }
}

impl flatbuffers::Verifiable for Coord<'_> {
  #[inline]
  fn run_verifier(
    v: &mut flatbuffers::Verifier, pos: usize
  ) -> Result<(), flatbuffers::InvalidFlatbuffer> {
    use self::flatbuffers::Verifiable;
    v.visit_table(pos)?
     .visit_field::<i32>("x", Self::VT_X, false)?
     .visit_field::<i32>("y", Self::VT_Y, false)?
     .finish();
    Ok(())
  }
}
pub struct CoordArgs {
    pub x: i32,
    pub y: i32,
}
impl<'a> Default for CoordArgs {
  #[inline]
  fn default() -> Self {
    CoordArgs {
      x: 0,
      y: 0,
    }
  }
}

pub struct CoordBuilder<'a: 'b, 'b> {
  fbb_: &'b mut flatbuffers::FlatBufferBuilder<'a>,
  start_: flatbuffers::WIPOffset<flatbuffers::TableUnfinishedWIPOffset>,
}
impl<'a: 'b, 'b> CoordBuilder<'a, 'b> {
  #[inline]
  pub fn add_x(&mut self, x: i32) {
    self.fbb_.push_slot::<i32>(Coord::VT_X, x, 0);
  }
  #[inline]
  pub fn add_y(&mut self, y: i32) {
    self.fbb_.push_slot::<i32>(Coord::VT_Y, y, 0);
  }
  #[inline]
  pub fn new(_fbb: &'b mut flatbuffers::FlatBufferBuilder<'a>) -> CoordBuilder<'a, 'b> {
    let start = _fbb.start_table();
    CoordBuilder {
      fbb_: _fbb,
      start_: start,
    }
  }
  #[inline]
  pub fn finish(self) -> flatbuffers::WIPOffset<Coord<'a>> {
    let o = self.fbb_.end_table(self.start_);
    flatbuffers::WIPOffset::new(o.value())
  }
}

impl core::fmt::Debug for Coord<'_> {
  fn fmt(&self, f: &mut core::fmt::Formatter<'_>) -> core::fmt::Result {
    let mut ds = f.debug_struct("Coord");
      ds.field("x", &self.x());
      ds.field("y", &self.y());
      ds.finish()
  }
}
pub enum LabelOffset {}
#[derive(Copy, Clone, PartialEq)]

pub struct Label<'a> {
  pub _tab: flatbuffers::Table<'a>,
}

impl<'a> flatbuffers::Follow<'a> for Label<'a> {
  type Inner = Label<'a>;
  #[inline]
  unsafe fn follow(buf: &'a [u8], loc: usize) -> Self::Inner {
    Self { _tab: flatbuffers::Table::new(buf, loc) }
  }
}

impl<'a> Label<'a> {
  pub const VT_TEXT: flatbuffers::VOffsetT = 4;
  pub const VT_COLOR: flatbuffers::VOffsetT = 6;
  pub const VT_POSITION: flatbuffers::VOffsetT = 8;

  #[inline]
  pub unsafe fn init_from_table(table: flatbuffers::Table<'a>) -> Self {
    Label { _tab: table }
  }
  #[allow(unused_mut)]
  pub fn create<'bldr: 'args, 'args: 'mut_bldr, 'mut_bldr>(
    _fbb: &'mut_bldr mut flatbuffers::FlatBufferBuilder<'bldr>,
    args: &'args LabelArgs<'args>
  ) -> flatbuffers::WIPOffset<Label<'bldr>> {
    let mut builder = LabelBuilder::new(_fbb);
    if let Some(x) = args.position { builder.add_position(x); }
    if let Some(x) = args.color { builder.add_color(x); }
    if let Some(x) = args.text { builder.add_text(x); }
    builder.finish()
  }


  #[inline]
  pub fn text(&self) -> Option<&'a str> {
    // Safety:
    // Created from valid Table for this object
    // which contains a valid value in this slot
    unsafe { self._tab.get::<flatbuffers::ForwardsUOffset<&str>>(Label::VT_TEXT, None)}
  }
  #[inline]
  pub fn color(&self) -> Option<&'a str> {
    // Safety:
    // Created from valid Table for this object
    // which contains a valid value in this slot
    unsafe { self._tab.get::<flatbuffers::ForwardsUOffset<&str>>(Label::VT_COLOR, None)}
  }
  #[inline]
  pub fn position(&self) -> Option<Coord<'a>> {
    // Safety:
    // Created from valid Table for this object
    // which contains a valid value in this slot
    unsafe { self._tab.get::<flatbuffers::ForwardsUOffset<Coord>>(Label::VT_POSITION, None)}
  }
}

impl flatbuffers::Verifiable for Label<'_> {
  #[inline]
  fn run_verifier(
    v: &mut flatbuffers::Verifier, pos: usize
  ) -> Result<(), flatbuffers::InvalidFlatbuffer> {
    use self::flatbuffers::Verifiable;
    v.visit_table(pos)?
     .visit_field::<flatbuffers::ForwardsUOffset<&str>>("text", Self::VT_TEXT, false)?
     .visit_field::<flatbuffers::ForwardsUOffset<&str>>("color", Self::VT_COLOR, false)?
     .visit_field::<flatbuffers::ForwardsUOffset<Coord>>("position", Self::VT_POSITION, false)?
     .finish();
    Ok(())
  }
}
pub struct LabelArgs<'a> {
    pub text: Option<flatbuffers::WIPOffset<&'a str>>,
    pub color: Option<flatbuffers::WIPOffset<&'a str>>,
    pub position: Option<flatbuffers::WIPOffset<Coord<'a>>>,
}
impl<'a> Default for LabelArgs<'a> {
  #[inline]
  fn default() -> Self {
    LabelArgs {
      text: None,
      color: None,
      position: None,
    }
  }
}

pub struct LabelBuilder<'a: 'b, 'b> {
  fbb_: &'b mut flatbuffers::FlatBufferBuilder<'a>,
  start_: flatbuffers::WIPOffset<flatbuffers::TableUnfinishedWIPOffset>,
}
impl<'a: 'b, 'b> LabelBuilder<'a, 'b> {
  #[inline]
  pub fn add_text(&mut self, text: flatbuffers::WIPOffset<&'b  str>) {
    self.fbb_.push_slot_always::<flatbuffers::WIPOffset<_>>(Label::VT_TEXT, text);
  }
  #[inline]
  pub fn add_color(&mut self, color: flatbuffers::WIPOffset<&'b  str>) {
    self.fbb_.push_slot_always::<flatbuffers::WIPOffset<_>>(Label::VT_COLOR, color);
  }
  #[inline]
  pub fn add_position(&mut self, position: flatbuffers::WIPOffset<Coord<'b >>) {
    self.fbb_.push_slot_always::<flatbuffers::WIPOffset<Coord>>(Label::VT_POSITION, position);
  }
  #[inline]
  pub fn new(_fbb: &'b mut flatbuffers::FlatBufferBuilder<'a>) -> LabelBuilder<'a, 'b> {
    let start = _fbb.start_table();
    LabelBuilder {
      fbb_: _fbb,
      start_: start,
    }
  }
  #[inline]
  pub fn finish(self) -> flatbuffers::WIPOffset<Label<'a>> {
    let o = self.fbb_.end_table(self.start_);
    flatbuffers::WIPOffset::new(o.value())
  }
}

impl core::fmt::Debug for Label<'_> {
  fn fmt(&self, f: &mut core::fmt::Formatter<'_>) -> core::fmt::Result {
    let mut ds = f.debug_struct("Label");
      ds.field("text", &self.text());
      ds.field("color", &self.color());
      ds.field("position", &self.position());
      ds.finish()
  }
}
#[inline]
/// Verifies that a buffer of bytes contains a `Label`
/// and returns it.
/// Note that verification is still experimental and may not
/// catch every error, or be maximally performant. For the
/// previous, unchecked, behavior use
/// `root_as_label_unchecked`.
pub fn root_as_label(buf: &[u8]) -> Result<Label, flatbuffers::InvalidFlatbuffer> {
  flatbuffers::root::<Label>(buf)
}
#[inline]
/// Verifies that a buffer of bytes contains a size prefixed
/// `Label` and returns it.
/// Note that verification is still experimental and may not
/// catch every error, or be maximally performant. For the
/// previous, unchecked, behavior use
/// `size_prefixed_root_as_label_unchecked`.
pub fn size_prefixed_root_as_label(buf: &[u8]) -> Result<Label, flatbuffers::InvalidFlatbuffer> {
  flatbuffers::size_prefixed_root::<Label>(buf)
}
#[inline]
/// Verifies, with the given options, that a buffer of bytes
/// contains a `Label` and returns it.
/// Note that verification is still experimental and may not
/// catch every error, or be maximally performant. For the
/// previous, unchecked, behavior use
/// `root_as_label_unchecked`.
pub fn root_as_label_with_opts<'b, 'o>(
  opts: &'o flatbuffers::VerifierOptions,
  buf: &'b [u8],
) -> Result<Label<'b>, flatbuffers::InvalidFlatbuffer> {
  flatbuffers::root_with_opts::<Label<'b>>(opts, buf)
}
#[inline]
/// Verifies, with the given verifier options, that a buffer of
/// bytes contains a size prefixed `Label` and returns
/// it. Note that verification is still experimental and may not
/// catch every error, or be maximally performant. For the
/// previous, unchecked, behavior use
/// `root_as_label_unchecked`.
pub fn size_prefixed_root_as_label_with_opts<'b, 'o>(
  opts: &'o flatbuffers::VerifierOptions,
  buf: &'b [u8],
) -> Result<Label<'b>, flatbuffers::InvalidFlatbuffer> {
  flatbuffers::size_prefixed_root_with_opts::<Label<'b>>(opts, buf)
}
#[inline]
/// Assumes, without verification, that a buffer of bytes contains a Label and returns it.
/// # Safety
/// Callers must trust the given bytes do indeed contain a valid `Label`.
pub unsafe fn root_as_label_unchecked(buf: &[u8]) -> Label {
  flatbuffers::root_unchecked::<Label>(buf)
}
#[inline]
/// Assumes, without verification, that a buffer of bytes contains a size prefixed Label and returns it.
/// # Safety
/// Callers must trust the given bytes do indeed contain a valid size prefixed `Label`.
pub unsafe fn size_prefixed_root_as_label_unchecked(buf: &[u8]) -> Label {
  flatbuffers::size_prefixed_root_unchecked::<Label>(buf)
}
#[inline]
pub fn finish_label_buffer<'a, 'b>(
    fbb: &'b mut flatbuffers::FlatBufferBuilder<'a>,
    root: flatbuffers::WIPOffset<Label<'a>>) {
  fbb.finish(root, None);
}

#[inline]
pub fn finish_size_prefixed_label_buffer<'a, 'b>(fbb: &'b mut flatbuffers::FlatBufferBuilder<'a>, root: flatbuffers::WIPOffset<Label<'a>>) {
  fbb.finish_size_prefixed(root, None);
}
}  // pub mod Label
}  // pub mod Output
}  // pub mod CoffeeTime

